default: &default
  adapter: postgresql
  encoding: utf8
  host: localhost
  port: 5432
  username: msf_user
  password: msf_user
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: msf_development

test:
  <<: *default
  database: msf_test

production:
  <<: *default
  database: msf_production